language: csharp
mono: none
dotnet: 2.1.4
solution: Rpg.sln

notifications:
  email: false

install:
  - dotnet restore

script:
  - dotnet build --no-restore -c Release
  - dotnet test ./tests/Rpg.Models.Tests/Rpg.Models.Tests.csproj --no-build --no-restore -c Release
  - dotnet test ./tests/Rpg.Logic.Tests/Rpg.Logic.Tests.csproj --no-build --no-restore -c Release
  - dotnet test ./tests/Rpg.Commands.Tests/Rpg.Commands.Tests.csproj --no-build --no-restore -c Release
